### ISSUE TITLE
Let's Encript

### ISSUE THREAD

**Issue by HughP** [sm0k3net/WordPress#1]
Have you ever used or installed a https://letsencrypt.org/ cert? I have seen a demo of code that actually creates the certs via something like an API I am guessing. Just wondering if you have used something like that. That might up the security settings on your WordPress script some.

**Comment by sm0k3net** [comment]
Hi,
Yes, I'm using Let's Encrypt because it was much easier to integrate with my LAMP script :)
I have already created one script which installs LAMP + SSL, when I will get some spare time, will do the same for nginx version as well.

https://github.com/sm0k3net/WordPress/blob/master/wp_lamp_https.sh - this one works with SSL (Let's Encrypt) setting proper configuration file, so you will get at least "A" rank on ssltest.

Thank you for your interest.

Best regards,
Uladzislau Murashka

**Comment by sm0k3net** [comment]
Closed.
